sudo: false

language: node_js
node_js:
  - 13

before_install:
  - npm install coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master